In [1]:
%pylab inline
import pandas as pd
from sklearn.model_selection import cross_val_predict
from sklearn.svm import SVC
from sklearn.utils import shuffle
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score

Populating the interactive namespace from numpy and matplotlib


In [2]:
df = pd.read_csv('kddcup.data_10_percent1.csv', header=None)

In [5]:
df[41].describe()

count    494021.000000
mean         -0.606179
std           0.795329
min          -1.000000
25%          -1.000000
50%          -1.000000
75%          -1.000000
max           1.000000
Name: 41, dtype: float64

In [6]:
df.groupby(41)[41].count()

41
-1    396743
 1     97278
Name: 41, dtype: int64

In [7]:
df.shape

(494021, 42)

In [8]:
df[41].unique()

array([ 1, -1], dtype=int64)

In [9]:
X, y = df[list(range(41))].values, df[41].map({1:1, -1:0}).values

In [10]:
X.shape, y.shape

((494021L, 41L), (494021L,))

In [11]:
X, y = shuffle(X, y)

In [12]:
n_samples = 5000
Xi, yi = X[:n_samples], y[:n_samples]

In [15]:
clf = SVC()
predicted = cross_val_predict(clf, Xi, yi, cv=3)

In [16]:
print confusion_matrix(yi, predicted)
print f1_score(yi, predicted)

[[3888  116]
 [   0  996]]
0.944971537002


In [17]:
clf = SVC()
clf.fit(Xi, yi)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [22]:
predicted = clf.predict(X[:50000])

In [24]:
print confusion_matrix(y[:50000], predicted)
print f1_score(y[:50000], predicted)

[[39290  1025]
 [    0  9685]]
0.949742583967
